// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCti-NhLuJ7RW8k8ybIOl7aHD7PJzRsm8E',
    appId: '1:438310024831:web:7210163c42cbf6ff49f14a',
    messagingSenderId: '438310024831',
    projectId: 'chat-64052',
    authDomain: 'chat-64052.firebaseapp.com',
    storageBucket: 'chat-64052.firebasestorage.app',
    measurementId: 'G-TJTZ4XYJ40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBze-5v8H35NdNen-V3-RY-ogfKODBXviY',
    appId: '1:438310024831:android:60c364e7e7fc84d649f14a',
    messagingSenderId: '438310024831',
    projectId: 'chat-64052',
    storageBucket: 'chat-64052.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Dg82EsTzle8bEZ8dZI974y5RjgqHVas',
    appId: '1:438310024831:ios:bddd33ecfeb186a949f14a',
    messagingSenderId: '438310024831',
    projectId: 'chat-64052',
    storageBucket: 'chat-64052.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Dg82EsTzle8bEZ8dZI974y5RjgqHVas',
    appId: '1:438310024831:ios:bddd33ecfeb186a949f14a',
    messagingSenderId: '438310024831',
    projectId: 'chat-64052',
    storageBucket: 'chat-64052.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCti-NhLuJ7RW8k8ybIOl7aHD7PJzRsm8E',
    appId: '1:438310024831:web:1e750b7d4f60e4cd49f14a',
    messagingSenderId: '438310024831',
    projectId: 'chat-64052',
    authDomain: 'chat-64052.firebaseapp.com',
    storageBucket: 'chat-64052.firebasestorage.app',
    measurementId: 'G-XRLKZH58TW',
  );
}
